import { defineConfig } from "oxlint";

export default defineConfig({
  options: {
    typeAware: true,
  },
  categories: {
    correctness: "warn",
  },
  ignorePatterns: ["dist/", "src/**/*.generated.ts"],
  plugins: ["eslint", "typescript", "unicorn", "oxc", "import", "promise"],
  rules: {
    // eslint/pedantic
    eqeqeq: "error",
    "max-depth": "error",
    "no-array-constructor": "error",
    "no-case-declarations": "error",
    "no-constructor-return": "error",
    "no-else-return": "error",
    "no-inline-comments": "error",
    "no-inner-declarations": "error",
    "no-lonely-if": "error",
    "no-loop-func": "error",
    "no-new-wrappers": "error",
    "no-object-constructor": "error",
    "no-promise-executor-return": "error",
    "no-useless-return": "error",
    radix: "error",

    // eslint/perf
    "no-await-in-loop": "error",
    "no-useless-call": "error",

    // eslint/restriction
    "no-bitwise": "error",
    "no-console": "error",
    "no-div-regex": "error",
    "no-empty": "error",
    "no-empty-function": "error",
    "no-param-reassign": "error",
    "no-proto": "error",
    "no-regex-spaces": "error",
    "unicode-bom": "error",

    // eslint/style
    curly: "error",
    "default-param-last": "error",
    "func-style": ["error", "declaration", { allowArrowFunctions: false }],
    "guard-for-in": "error",
    "max-params": "error",
    "no-lone-blocks": "error",
    "no-multi-assign": "error",
    "no-nested-ternary": "error",
    "no-return-assign": "error",
    "no-useless-computed-key": "error",
    "operator-assignment": "error",
    "prefer-const": "error",
    "prefer-destructuring": "error",
    "prefer-exponentiation-operator": "error",
    "prefer-numeric-literals": "error",
    "prefer-object-has-own": "error",
    "prefer-object-spread": "error",
    "prefer-promise-reject-errors": "error",
    "prefer-rest-params": "error",
    "sort-imports": "error",
    yoda: "error",

    // eslint /suspicious
    "no-unmodified-loop-condition": "error",
    "no-unneeded-ternary": "error",
    "preserve-caught-error": "error",

    // import
    "import/export": "error",
    "import/named": "error",
    "import/no-cycle": "error",
    "import/consistent-type-specifier-style": "error",
    "import/first": "error",
    "import/no-duplicates": "error",
    "import/no-mutable-exports": "error",
    "import/no-self-import": "error",

    // oxc
    "oxc/no-accumulating-spread": "error",
    "oxc/no-map-spread": "error",
    "oxc/bad-bitwise-operator": "error",
    "oxc/no-barrel-file": "error",
    "oxc/no-const-enum": "error",
    "oxc/approx-constant": "error",
    "oxc/misrefactored-assign-op": "error",

    // promise
    "promise/always-return": "error",
    "promise/catch-or-return": "error",
    "promise/no-callback-in-promise": "error",
    "promise/no-multiple-resolved": "error",
    "promise/no-nesting": "error",
    "promise/no-new-statics": "error",
    "promise/no-promise-in-callback": "error",
    "promise/no-return-in-finally": "error",
    "promise/no-return-wrap": "error",
    "promise/param-names": "error",
    "promise/prefer-await-to-callbacks": "error",
    "promise/prefer-await-to-then": "error",
    "promise/prefer-catch": "error",
    "promise/spec-only": "error",
    "promise/valid-params": "error",

    // typescript
    "typescript/consistent-return": "error",
    "typescript/consistent-type-exports": "error",
    "typescript/no-unnecessary-condition": "error",
    "typescript/no-unnecessary-qualifier": "error",
    "typescript/no-unnecessary-type-parameters": "error",
    "typescript/no-useless-default-assignment": "error",
    "typescript/prefer-optional-chain": "error",
    "typescript/prefer-readonly": "error",
    "typescript/prefer-readonly-parameter-types": "off",
    "typescript/prefer-regexp-exec": "error",
    "typescript/ban-ts-comment": "error",
    "typescript/no-misused-promises": "error",
    "typescript/only-throw-error": "error",
    "typescript/prefer-includes": "error",
    "typescript/prefer-nullish-coalescing": "error",
    "typescript/prefer-promise-reject-errors": "error",
    "typescript/prefer-ts-expect-error": "error",
    "typescript/require-await": "error",
    "typescript/return-await": "error",
    "typescript/strict-boolean-expressions": "error",
    "typescript/switch-exhaustiveness-check": "error",
    "typescript/explicit-function-return-type": "error",
    "typescript/no-dynamic-delete": "error",
    "typescript/no-empty-object-type": "error",
    "typescript/no-explicit-any": "error",
    "typescript/no-import-type-side-effects": "error",
    "typescript/no-namespace": "error",
    "typescript/no-non-null-asserted-nullish-coalescing": "error",
    "typescript/no-non-null-assertion": "error",
    "typescript/no-restricted-types": "error",
    "typescript/prefer-literal-enum-member": "error",
    "typescript/promise-function-async": "error",
    "typescript/array-type": "error",
    "typescript/class-literal-property-style": "error",
    "typescript/consistent-type-definitions": ["error", "type"],
    "typescript/consistent-type-imports": "error",
    "typescript/no-inferrable-types": "error",
    "typescript/prefer-for-of": "error",
    "typescript/prefer-reduce-type-parameter": "error",
    "typescript/prefer-return-this-type": "error",
    "typescript/unified-signatures": "error",
    "typescript/no-unnecessary-boolean-literal-compare": "error",
    "typescript/no-unnecessary-template-expression": "error",
    "typescript/no-unnecessary-type-arguments": "error",
    "typescript/no-unnecessary-type-assertion": "error",
    "typescript/no-unnecessary-type-constraint": "error",
    "typescript/no-unsafe-type-assertion": "error",

    // unicorn
    "unicorn/consistent-assert": "error",
    "unicorn/consistent-empty-array-spread": "error",
    "unicorn/escape-case": "error",
    "unicorn/explicit-length-check": "error",
    "unicorn/new-for-builtins": "error",
    "unicorn/no-array-callback-reference": "error",
    "unicorn/no-hex-escape": "error",
    "unicorn/no-instanceof-array": "error",
    "unicorn/no-negation-in-equality-check": "error",
    "unicorn/no-new-buffer": "error",
    "unicorn/no-object-as-default-parameter": "error",
    "unicorn/no-typeof-undefined": "error",
    "unicorn/no-unnecessary-array-flat-depth": "error",
    "unicorn/no-unnecessary-array-splice-count": "error",
    "unicorn/no-unnecessary-slice-end": "error",
    "unicorn/no-unreadable-iife": "error",
    "unicorn/no-useless-promise-resolve-reject": "error",
    "unicorn/no-useless-undefined": "error",
    "unicorn/prefer-array-flat": "error",
    "unicorn/prefer-array-some": "error",
    "unicorn/prefer-at": "error",
    "unicorn/prefer-blob-reading-methods": "error",
    "unicorn/prefer-code-point": "error",
    "unicorn/prefer-date-now": "error",
    "unicorn/prefer-dom-node-append": "error",
    "unicorn/prefer-dom-node-dataset": "error",
    "unicorn/prefer-dom-node-remove": "error",
    "unicorn/prefer-event-target": "error",
    "unicorn/prefer-math-min-max": "error",
    "unicorn/prefer-math-trunc": "error",
    "unicorn/prefer-native-coercion-functions": "error",
    "unicorn/prefer-prototype-methods": "error",
    "unicorn/prefer-regexp-test": "error",
    "unicorn/prefer-string-replace-all": "error",
    "unicorn/prefer-string-slice": "error",
    "unicorn/prefer-top-level-await": "error",
    "unicorn/prefer-type-error": "error",
    "unicorn/require-number-to-fixed-digits-argument": "error",
    "unicorn/prefer-array-find": "error",
    "unicorn/prefer-array-flat-map": "error",
    "unicorn/prefer-set-has": "error",
    "unicorn/no-array-for-each": "error",
    "unicorn/no-document-cookie": "error",
    "unicorn/no-length-as-slice-end": "error",
    "unicorn/no-magic-array-flat-depth": "error",
    "unicorn/no-process-exit": "error",
    "unicorn/no-useless-error-capture-stack-trace": "error",
    "unicorn/prefer-modern-math-apis": "error",
    "unicorn/prefer-module": "error",
    "unicorn/prefer-node-protocol": "error",
    "unicorn/prefer-number-properties": "error",
    "unicorn/catch-error-name": "error",
    "unicorn/consistent-date-clone": "error",
    "unicorn/empty-brace-spaces": "error",
    "unicorn/no-array-method-this-argument": "error",
    "unicorn/no-await-expression-member": "error",
    "unicorn/no-unreadable-array-destructuring": "error",
    "unicorn/no-useless-collection-argument": "error",
    "unicorn/no-zero-fractions": "error",
    "unicorn/number-literal-case": "error",
    "unicorn/numeric-separators-style": "error",
    "unicorn/prefer-array-index-of": "error",
    "unicorn/prefer-bigint-literals": "error",
    "unicorn/prefer-class-fields": "error",
    "unicorn/prefer-classlist-toggle": "error",
    "unicorn/prefer-default-parameters": "error",
    "unicorn/prefer-dom-node-text-content": "error",
    "unicorn/prefer-global-this": "error",
    "unicorn/prefer-keyboard-event-key": "error",
    "unicorn/prefer-logical-operator-over-ternary": "error",
    "unicorn/prefer-modern-dom-apis": "error",
    "unicorn/prefer-negative-index": "error",
    "unicorn/prefer-object-from-entries": "error",
    "unicorn/prefer-optional-catch-binding": "error",
    "unicorn/prefer-reflect-apply": "error",
    "unicorn/prefer-response-static-json": "error",
    "unicorn/prefer-spread": "error",
    "unicorn/prefer-string-raw": "error",
    "unicorn/prefer-string-trim-start-end": "error",
    "unicorn/prefer-structured-clone": "error",
    "unicorn/relative-url-style": "error",
    "unicorn/require-array-join-separator": "error",
    "unicorn/require-module-attributes": "error",
    "unicorn/switch-case-braces": "error",
    "unicorn/text-encoding-identifier-case": "error",
    "unicorn/throw-new-error": "error",
    "unicorn/consistent-function-scoping": "error",
    "unicorn/no-accessor-recursion": "error",
    "unicorn/no-array-reverse": "error",
    "unicorn/no-array-sort": "error",
    "unicorn/no-instanceof-builtins": "error",
    "unicorn/require-post-message-target-origin": "error",
  },
  overrides: [
    {
      files: ["**/*.test.ts", "**/*.test.tsx"],
      plugins: ["vitest", "jest"],
      rules: {
        // vitest
        "vitest/consistent-test-filename": [
          "error",
          {
            allTestPattern: "(__test__|__tests__|\\.test\\.)",
            pattern: "^(?!.*\\/__tests?__\\/).*\\.test\\.[cm]?[jt]sx?$",
          },
        ],
        "vitest/consistent-test-it": ["error", { fn: "test" }],
        "vitest/consistent-each-for": "error",
        "vitest/hoisted-apis-on-top": "error",
        "vitest/no-conditional-tests": "error",
        "vitest/require-local-test-context-for-concurrent-snapshots": "error",
        "vitest/consistent-vitest-vi": "error",
        "vitest/no-import-node-test": "error",
        "vitest/prefer-called-once": "error",
        "vitest/prefer-called-times": "off",
        "vitest/prefer-called-with": "error",
        "vitest/prefer-describe-function-title": "error",
        "vitest/prefer-expect-type-of": "error",
        "vitest/prefer-import-in-mock": "error",
        "vitest/prefer-to-be-falsy": "error",
        "vitest/prefer-to-be-object": "error",
        "vitest/prefer-to-be-truthy": "error",
        "vitest/expect-expect": "error",
        "vitest/no-standalone-expect": "error",
        "vitest/valid-describe-callback": "error",
        "vitest/valid-expect": "error",
        "vitest/no-test-return-statement": "error",
        "vitest/no-unneeded-async-expect-function": "error",
        "vitest/prefer-strict-equal": "error",
        "vitest/prefer-comparison-matcher": "error",
        "vitest/prefer-hooks-on-top": "error",
        "vitest/prefer-hooks-in-order": "error",
        "vitest/prefer-mock-promise-shorthand": "error",
        "vitest/prefer-mock-return-shorthand": "error",
        "vitest/prefer-spy-on": "error",
        "vitest/prefer-to-be": "error",
        "vitest/prefer-to-contain": "error",
        "vitest/prefer-to-have-length": "error",
        "vitest/prefer-todo": "error",
        "vitest/require-hook": "error",
        "vitest/require-top-level-describe": "error",
        "vitest/no-commented-out-tests": "error",
        // jest
        "jest/no-export": "error",
        "jest/require-to-throw-message": "error",
        "jest/valid-title": "off",
        "jest/max-nested-describe": "error",
      },
    },
  ],
});
